name: alkilate
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  cupertino_icons: ^1.0.8
  cloud_firestore: ^5.6.2
  firebase_auth: ^5.4.1
  google_sign_in: ^5.2.1
  firebase_core: ^3.10.1 # Use a version compatible with firebase_auth
  font_awesome_flutter: ^10.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/images/
  uses-material-design: true
