name: alkilate
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  cupertino_icons: ^1.0.8
  cloud_firestore: ^5.6.2
  firebase_auth: ^5.4.1
  google_sign_in: ^5.2.1
  firebase_core: ^3.10.1
  font_awesome_flutter: ^10.8.0
  smooth_page_indicator: ^1.0.0
  flutter_rating_bar: ^4.0.0
  google_maps_flutter: ^2.0.6
  json_annotation: ^4.9.0
  rxdart: ^0.27.2
  uuid: ^4.2.2
  flutter_custom_tabs: ^2.1.0
  url_launcher: ^6.0.13

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.1.4
  json_serializable: ^6.0.0

flutter:
  assets:
    - assets/images/
  uses-material-design: true
