name: alkilate
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  cupertino_icons: ^1.0.8
  cloud_firestore: ^5.6.4
  firebase_auth: ^5.5.0
  google_sign_in: ^6.2.2
  firebase_core: ^3.12.0
  firebase_storage: ^12.4.3
  font_awesome_flutter: ^10.8.0
  smooth_page_indicator: ^1.2.1
  flutter_rating_bar: ^4.0.0
  google_maps_flutter: ^2.10.1
  json_annotation: ^4.9.0
  rxdart: ^0.28.0
  uuid: ^4.2.2
  flutter_custom_tabs: ^2.1.0
  url_launcher: ^6.0.13
  http: ^1.3.0
  file_picker: ^9.0.1
  flutter_svg: ^2.0.7
  geolocator: ^9.0.2
  intl: ^0.20.2
  location: ^5.0.0
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.1.4
  json_serializable: ^6.0.0

flutter:
  assets:
    - assets/images/
    - assets/svg/
  uses-material-design: true
